---
- name: This play is used to start ec2 instance 
  hosts: localhost 
  connection: local 
  gather_facts: false 
  tasks:
    - name: starting ec2 instance 
      ec2:
        instance_ids: i-060cfae3106e4817c
        region: us-east-1
        state: stopped

