---
- name: This play is used to start ec2 instance 
  hosts: localhost 
  connection: local 
  gather_facts: false 
  vars:
    stopped_instance_ids: [i-060cfae3106e4817c]
  tasks:
    - name: stopping ec2 instance 
      shell: |
        aws ec2 stop-instances --instance-ids "{{item}}" --region us-east-1
      with_items: "{{stopped_instance_ids}}"
      

